apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: file-updates-test-rpa
  namespace: managed-release-team-tenant
spec:
  applications:
    - fileupdatestest
  origin: dev-release-team-tenant
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: https://github.com/redhat-appstudio/release-service-catalog.git
        - name: revision
          value: production
        - name: pathInRepo
          value: pipelines/rh-push-to-external-registry/push-to-external-registry.yaml
      resolver: "git"
    serviceAccountName: release-service-account
  policy: file-updates-test-policy
  data:
    fileUpdates:
      - paths:
        - path: data/services/ocm/osd-fleet-manager/cicd/deploy.yaml
          replacements:
          - key: "(.resourceTemplates[] | select(.name==\"osd-fleet-manager-integration\") | .parameters.HYPERSHIFT_OPERATOR_OVERRIDING_DATA)"
            replacement: "|hypershift-operator:.*|hypershift-operator: {{ .components[] | select(.name==\"fileupdatestest-component\") | [.repository, .containerImage |split(\"@\").[1] ] |join(\"@\")}}|"
        ref: master
        upstream_repo: https://gitlab.cee.redhat.com/shebert/app-interface.git
        repo: https://gitlab.cee.redhat.com/hacbs-release-tests/app-interface.git
    pyxis:
      server: stage
      secret: pyxis
    images:
      addGitShaTag: true
    mapping:
      components:
        - name: fileupdatestest-component
          repository: quay.io/hacbs-release-tests/fileupdatestest-component

