apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: e2e-fbc-stage-index-releaseplan
  namespace: dev-release-team-tenant
spec:
  application: e2e-fbc-stage-index-application
  target: managed-release-team-tenant
