apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: rhtap-service-push-rp
spec:
  application: rhtap-service-push-app
  target: managed-release-team-tenant
