apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rh-push-to-registry-redhat-io-test-rpa
  namespace: managed-release-team-tenant
spec:
  applications:
    - rh-push-to-registry-redhat-iotest
  origin: dev-release-team-tenant
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: https://github.com/theflockers/release-service-catalog.git
        - name: revision
          value:  release_1
        - name: pathInRepo
          value: pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
      resolver: "git"
    serviceAccountName: release-service-account
  policy: rh-push-to-registry-redhat-io-test-policy
  data:
    pyxis:
      server: stage
      secret: pyxis
    images:
      addGitShaTag: true
    mapping:
      components:
        - name: rh-push-to-registry-redhat-iotest-component
          repository: quay.io/lmendes/push-to-external-registry
